---

- name: Provision instances in NiftyCloud
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all

  tasks:
  - name: pip install requests
    pip:
      name: "requests"

  - name: launch server
    niftycloud:
      access_key: "{{ access_key }}"
      secret_access_key: "{{ secret_access_key }}"
      endpoint: "{{ endpoint }}"
      instance_id: "{{ instance_id_prefix }}{{ item }}"
      state: "running"
      image_id: "{{ image_id }}"
      key_name: "{{ key_name }}"
      security_group: "{{ fw_group_name }}"
      instance_type: "{{ instance_type }}"
      availability_zone: "{{ availability_zone }}"
      accounting_type: "{{ accounting_type }}"
      ip_type: "{{ ip_type }}"
    with_sequence: count=2

  - name: Regist server to load balancer
    niftycloud_lb:
      access_key: "{{ access_key }}"
      secret_access_key: "{{ secret_access_key }}"
      endpoint: "{{ endpoint }}"
      instance_id: "{{ instance_id_prefix }}{{ item }}"
      instance_port: "{{ instance_port }}"
      loadbalancer_name: "{{ loadbalancer_name }}"
      loadbalancer_port: "{{ loadbalancer_port }}"
      state: "present"
    with_sequence: count=2
